### ISSUE TITLE
Native builds fail with linking problem

### ISSUE THREAD

**Issue by glaubitz** [M680x0/M680x0-mono-repo#4]
After patching #3 as suggested, the native build continues for a while and then fails with due to a linking problem:

```
[ 30%] Linking CXX static library ../libLLVMCore.a
/usr/bin/ld: ../../lib/libLLVMM680x0Desc.a(M680x0MCTargetDesc.cpp.o): in function `createM680x0MCRelocationInfo(llvm::Triple const&, llvm::MCContext&)':
/glaubitz/M680x0-mono-repo/llvm/lib/Target/M680x0/MCTargetDesc/M680x0MCTargetDesc.cpp:100: undefined reference to `llvm::createMCRelocationInfo(llvm::Triple const&, llvm::MCContext&)'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/llvm-ml/CMakeFiles/llvm-ml.dir/build.make:111: bin/llvm-ml] Error 1
make[2]: Leaving directory '/glaubitz/M680x0-mono-repo/build'
make[1]: *** [CMakeFiles/Makefile2:18336: tools/llvm-ml/CMakeFiles/llvm-ml.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 30%] Linking CXX executable ../../bin/llvm-mca
make[2]: Leaving directory '/glaubitz/M680x0-mono-repo/build'
[ 30%] Built target LLVMCore
/usr/bin/ld: ../../lib/libLLVMM680x0Desc.a(M680x0MCTargetDesc.cpp.o): in function `createM680x0MCRelocationInfo(llvm::Triple const&, llvm::MCContext&)':
/glaubitz/M680x0-mono-repo/llvm/lib/Target/M680x0/MCTargetDesc/M680x0MCTargetDesc.cpp:100: undefined reference to `llvm::createMCRelocationInfo(llvm::Triple const&, llvm::MCContext&)'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/llvm-mca/CMakeFiles/llvm-mca.dir/build.make:292: bin/llvm-mca] Error 1
make[2]: Leaving directory '/glaubitz/M680x0-mono-repo/build'
make[1]: *** [CMakeFiles/Makefile2:18199: tools/llvm-mca/CMakeFiles/llvm-mca.dir/all] Error 2
make[1]: Leaving directory '/glaubitz/M680x0-mono-repo/build'
make: *** [Makefile:152: all] Error 2
```

I have not figured out yet what the problem is. Might be the ordering of libraries on the linker command line.

**Comment by mshockwave** [comment]
I can't reproduce this issue right now unfortunately. And I don't think this issue is highly related to our M680x0 part, since every `libLLVM<Target>Desc` library should not directly link with the library where `llvm::createMCRelocationInfo` resides in (i.e. libLLVMMCDisassembler), so the linker error was raised during the executable's (e.g. llvm-mca, llvm-ml above) linking stage.

Nevertheless, I'm currently using Ninja and LLD linker for my development tree (because i only have 32GB RAM on my machine and BFD linker, or even gold linker will easily exceed this limit!), which is different from your usage of GNU Make + BFD linker as hinted above. So maybe those are the causes.

Regardless, this issue is still worth investigating and I'll try to reproduce using your environment.

**Comment by glaubitz** [comment]
Did you try a native build? I don't see this issue when building on x86_64 either. So maybe it's running out of memory?

**Comment by mshockwave** [comment]
> Did you try a native build? I don't see this issue when building on x86_64 either. So maybe it's running out of memory?

I'm not sure what is 'native build' you're referring to here. If you're saying `LLVM_TARGETS_TO_BUILD` cmake variable, currently I've only turned on X86 and M680x0.

**Comment by glaubitz** [comment]
With native build I mean on an 68000 emulator, i.e. qemu-m68k.

**Comment by mshockwave** [comment]
Oh I haven't tried that yet. I'll do that when I got a chance

**Comment by glaubitz** [comment]
I just did a ```git pull``` again and I can no longer reproduce the problem for native builds. Guess we can close it then.
